moviestore:
  apiEndpointUrl: "https://api.themoviedb.org/3"
  apiKey: "c4e4545259f057acbb19e332a5fd8ace"
spring:
  redis:
    host: redis
    password:
    port: 6379
  session:
    store-type: redis
  thymeleaf:
    mode: HTML
    cache: false

