moviestore:
  apiEndpointUrl: "https://api.themoviedb.org/3"
  apiKey: ""
spring:
  redis:
    host: redis
    password:
    port: 6379
  session:
    store-type: redis
  thymeleaf:
    mode: HTML
    cache: false

