apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: lordofthejars/gateway:1.0.0
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 80