apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: movies
    version: v2
  name: movies-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movies
      version: v2
  template:
    metadata:
      labels:
        app: movies
        version: v2
    spec:
      containers:
      - env:
        - name: JAVA_OPTIONS
          value: -Xmx256m
        image: example/movies:v2
        imagePullPolicy: IfNotPresent
        name: movies
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        securityContext:
          privileged: false